SUPABASE_URL = "https://npuvrqtlshbbshbodyue.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdXZycXRsc2hiYnNoYm9keXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5OTExOTksImV4cCI6MjA5MTU2NzE5OX0.fIA8xQJxxR5dZ6dOJRXuxBk85MgON2CowqiN3he5-Ec"
GEOAPIFY_KEY = "af5b03a489d5409d875e9b11064a4817"
